resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/BuiXuanKhoi/Bookshop-project.git
      branch: master
jobs:

  - name: print-directory
    plan: 
      - get: source-code
        trigger: true
      -  task: print
         config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          run:
            path: sh
            args:
              - -exc
              - |
               ls 

  - name: build
    plan:
      - get: source-code
        trigger: true
      - file: source-code/ci/tasks/maven-package.yml
        task: package
        


  # - name: deploy
  #   plan:
  #     - get: source-code
  #       trigger: true
  #     - task: deploy
  #       config:
  #         platform: linux
  #         image_resource:
  #           type: docker-image
  #           source:
  #             repository: ubuntu
  #         inputs:
  #           - name: source-code
  #         run:
  #           path: source-code/ci/deploy.sh



