platform: linux

image_resource:
    type: docker-image
    source:
      repository: maven
      tag: 3-eclipse-temurin-17-alpine

inputs:
    - name: source-code
    - name: maven-cache

run:
    path: 'sh'
    args:
        - -exc
        - |
         cd source-code
         dir
         cp -r maven-cache/.m2 ..
         mvn clean package
