platform: linux

image_resource:
    type: docker-image
    source:
      repository: maven
      tag: 3-eclipse-temurin-17-alpine

inputs:
    - name: tested-source-code

run:
    path: 'mvn'
    args:
        - -f
        - source-code/pom.xml
        - clean
        - package
