platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3-eclipse-temurin-17-alpine

inputs:
  - name: source-code

outputs:
  - name: maven-cache

run:
  path: 'sh'
  args:
    - -exc
    - |
      cd source-code
      mvn clean test
      cd ..
      mv source-code/.m2 maven-cache